-- Schema for FDBDBA.FAC_LEASES_T table
-- Facility Leases Table - stores information about facility leases

CREATE TABLE FDBDBA.FAC_LEASES_T (
    FMSWIN_ID VARCHAR(50) NOT NULL,
    LEASE_ID VARCHAR(50) PRIMARY KEY,
    FACILITY_NAME VARCHAR(255),
    LEASE_START_DATE DATE,
    LEASE_END_DATE DATE,
    LEASE_AMOUNT DECIMAL(15,2),
    LEASE_STATUS VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create index on FMSWIN_ID for performance with the EXISTS query
CREATE INDEX idx_fac_leases_fmswin_id ON FDBDBA.FAC_LEASES_T(FMSWIN_ID);